id: telegram_bikes
alias: 'Return bikes stations state'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/bikes'
action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      message: >
        Place Barrois : {{ states.sensor.velostanlib_nancy_stations_2b6a62371b1b45a936468c9cf16a3528.state }}/17 bikes left
        {{'\n'}}Place de la Commanderie : {{ states.sensor.velostanlib_nancy_stations_10cd7436fee13bc82f9a1de82d55ae2f.state }}/18 bikes left
      disable_notification: true