id: telegram_disarm_alarm
alias: 'Telegram bot that disarm the alarm'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/disarm'
action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.ha_alarm
  - wait_template: "{{ is_state('alarm_control_panel.ha_alarm', 'disarmed') }}"
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      message: 'Alarm disarmed'
      disable_notification: true
