id: telegram_location
alias: 'Telegram bot that send the current location of the specified user'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/location'
condition:
  condition: or
  conditions:
    - condition: template
      value_template: "{{ trigger.event.data.args[0] is undefined }}"
    - condition: template
      value_template: "{{ trigger.event.data.args[0] == 'mp' or trigger.event.data.args[0] == 'matthieu' }}"
    - condition: template
      value_template: "{{ trigger.event.data.args[0] == 'jc' or trigger.event.data.args[0] == 'julie' }}"
action:
  - service_template: >
      {% if trigger.event.data.args[0] is defined %}
      telegram_bot.send_location
      {% else %}
      telegram_bot.send_message
      {% endif %}
    data_template:
      disable_notification: true
      target: '{{ trigger.event.data.chat_id }}'
      latitude: >
        {% if trigger.event.data.args[0] is defined %}
          {% if trigger.event.data.args[0] == 'mp' or trigger.event.data.args[0] == 'matthieu' %}
            {{ states.device_tracker.mp_s9.attributes.latitude }}
          {% elif trigger.event.data.args[0] == 'jc' or trigger.event.data.args[0] == 'julie' %}
            {{ states.device_tracker.jc_iphone.attributes.latitude }}
          {% endif %}
        {% endif %}
      longitude: >
        {% if trigger.event.data.args[0] is defined %}
          {% if trigger.event.data.args[0] == 'mp' or trigger.event.data.args[0] == 'matthieu' %}
            {{ states.device_tracker.mp_s9.attributes.longitude }}
          {% elif trigger.event.data.args[0] == 'jc' or trigger.event.data.args[0] == 'julie' %}
            {{ states.device_tracker.jc_iphone.attributes.longitude }}
          {% endif %}
        {% endif %}
      message: 'Provide a person. Like : "/location mp" or "/location jc"'
