id: telegram_speak
alias: 'Telegram bot that speak through Google Home'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/speak'
action:
  - service: tts.google_say
    entity_id: media_player.living_room_home
    data_template:
      language: "fr"
      cache: false
      message: >
        {{ trigger.event.data["from_first"] }} dit : {% for state in trigger.event.data["args"] %} {{ state }} {% endfor %}
