alias: "GeekInc started"
trigger:
  platform: state
  entity_id: sensor.studiorenegade
  to: streaming
condition:
  - condition: state
    entity_id: binary_sensor.is_someone_home
    state: "on"
  - condition: time
    after: '19:45:00'
    before: '21:00:00'
    weekday:
      - wed
action:
  - service: script.turn_on
    entity_id: script.geek_inc
#  - service: notify.google_assistant
#    data:
#      message: "C'est l'heure de StudioRenegade"
