- alias: "Washing done"
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition:
    condition: state
    entity_id: binary_sensor.washing_machine
    state: "on"
    for:
      hours: 0
      minutes: 1
      seconds: 0
  action:
    - service: notify.ifttt
      data: { "message": "Le linge est propre" }
    - condition: state
      entity_id: sensor.is_someone_home
      state: "on"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_home
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Le linge est propre"
        language: "fr"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_home
        volume_level: 0.3

#################
## Alarm 
#################
- alias: "Alarm armed"
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: armed_away
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Alarme activée"
        language: "fr"
    - service: script.turn_off
      entity_id: script.flash_light
    - service: script.turn_off
      entity_id: script.flash_light_loop
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_f0b429cc58ea
        brightness: 255
        color_name: red

- alias: "Alarm disarmed"
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: disarmed
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Alarme désactivée"
        language: "fr"
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_f0b429cc58ea 
    - service: script.turn_off
      entity_id: script.flash_light
    - service: script.turn_off
      entity_id: script.flash_light_loop

- alias: "Alarm triggered"
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: triggered
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Alerte ! Un intrus est arrivé"
        language: "fr"
    - service: notify.ifttt
      data: { "message": "Un intrus est dans l'appartement" }
    - service: script.flash_light
      data:
        light_entity_id: 'light.gateway_light_f0b429cc58ea'

- alias: "Arm alarm when away"
  trigger:
    platform: state
    entity_id: binary_sensor.is_someone_home
    from: "on"
    to: "off"
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm

- alias: "Disarm alarm when home"
  trigger:
    platform: state
    entity_id: binary_sensor.is_someone_home
    from: "off"
    to: "on"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm

- alias: "Trigger alarm"
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a1f304
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm



