- alias: "Washing is done IFTTT notification" 
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
    - service: ifttt.trigger
      data: { "event": "notification", "value1": "Washing is done" }

- alias: "Washing is done GH notification"
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition:
    condition: state
    entity_id: sensor.is_someone_home
    state: "yes"
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Le linge est propre"
        language: "fr"

- alias: "Alarm"
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001a1f304
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: sensor.is_someone_home
    state: "no"
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "Alerte ! Un intrus est arrivé"
        language: "fr"
    - service: ifttt.trigger
      data: { "event": "notification", "value1": "Someone passed the door" }
