- alias: "Washing is done IFTTT notification" 
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
    - service: ifttt.trigger
      data: { "event": "washing_done" }
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: "La machine à laver est terminée"
        language: "fr"
