- !include automation/alarm/arm.yaml
- !include automation/alarm/armed.yaml
- !include automation/alarm/disarm.yaml
- !include automation/alarm/disarmed.yaml
- !include automation/alarm/trigger.yaml
- !include automation/alarm/triggered.yaml

- !include automation/washing.yaml

# - !include automation/telegram/arm_callback.yaml
- !include automation/telegram/arm_command.yaml
# - !include automation/telegram/disarm_callback.yaml
- !include automation/telegram/disarm_command.yaml