- !include automation/alarm/armed.yaml
- !include automation/alarm/disarmed.yaml
- !include automation/alarm/trigger.yaml
- !include automation/alarm/triggered.yaml

- !include automation/presence/home.yaml
- !include automation/presence/away.yaml

- !include automation/lights/home.yaml

- !include automation/telegram/arm_callback.yaml
- !include automation/telegram/arm_command.yaml
- !include automation/telegram/bikes_command.yaml
- !include automation/telegram/disarm_callback.yaml
- !include automation/telegram/disarm_command.yaml
- !include automation/telegram/location_command.yaml
- !include automation/telegram/speak_command.yaml
- !include automation/telegram/start_command.yaml

- !include automation/theme/dark_theme_at_night.yaml
- !include automation/theme/light_theme_at_day.yaml

- !include automation/bikes/almost_empty_PlaceBarrois.yaml
- !include automation/bikes/almost_empty_PlaceCommanderie.yaml

- !include automation/washing.yaml
- !include automation/geekinc.yaml
