# Washing Machine
- platform: mqtt
  name: "Washing Machine"
  state_topic: "stat/washing_machine/RESULT"
  value_template: "{{ value_json['POWER'] }}"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0
  retain: true

# Test if somehome is currently at home
- platform: template
  sensors:
    is_someone_home:
      value_template: >-
        {%- if is_state("group.matthieu", "home")
        or is_state("group.julie", "home")
        -%}
          True
        {%- else -%}
          False
        {%- endif %}
      entity_id:
        - group.matthieu
        - group.julie
