# Washing Machine
- platform: mqtt
  name: "Washing Machine"
  state_topic: "washing-machine/state"
  payload_on: "1"
  payload_off: "0"
  qos: 1
  retain: true

- platform: template
  sensors:
    is_someone_home:
      value_template: >-
        {%- if is_state("device_tracker.mp_z3c", "home")
        or is_state("device_tracker.mp_macbook_air", "home")
        or is_state("device_tracker.jc_iphone", "on")
        or is_state("device_tracker.jc_macbook_air", "on")
        -%}
          True
        {%- else -%}
          False
        {%- endif %}
      entity_id:
        - device_tracker.mp_z3c
        - device_tracker.mp_macbook_air
        - device_tracker.jc_iphone
        - device_tracker.jc_macbook_air
