#- platform: mjpeg
#  mjpeg_url: http://127.0.0.1:8081/html/cam_pic_new.php
#  name: "RPi Camera"

- platform: generic
  name: Locations
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?size=800x800&maptype=satellite&markers=color:blue|label:M|{{ states.device_tracker.mp_z3c.attributes.latitude }},{{ states.device_tracker.mp_z3c.attributes.longitude }}&markers=color:pink|label:J|{{ states.device_tracker.jc_iphone.attributes.latitude }},{{ states.device_tracker.jc_iphone.attributes.longitude }}
  limit_refetch_to_url_change: true