- platform: generic_thermostat
  name: Living room
  heater: sensor.temperature_158d0001a23103
  target_sensor: sensor.temperature_158d0001a23103
  initial_operation_mode: 'off'

- platform: generic_thermostat
  name: Bathroom
  heater: sensor.temperature_158d0001a35a71
  target_sensor: sensor.temperature_158d0001a35a71
  initial_operation_mode: 'off'

- platform: generic_thermostat
  name: Bedroom  
  heater: sensor.bedroom_temperature
  target_sensor: sensor.bedroom_temperature
  initial_operation_mode: 'off'
#  ac_mode: true

#- platform: eq3btsmart
#  devices:
#    bedroom:
#      mac: !secret eq3bt_bedroom_mac
