- platform: generic_thermostat
  name: Thermostat
  heater: sensor.temperature_158d0001a23103
  target_sensor: sensor.temperature_158d0001a23103
#  ac_mode: true

#- platform: eq3btsmart
#  devices:
#    bedroom:
#      mac: !secret eq3bt_bedroom_mac
