homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.358707
  longitude: 6.167673
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 156
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

logger: !include logger.yaml

# Enable the frontend
frontend: !include frontend.yaml

# Enable Hassio configuration
hassio:

# Enable configuration UI
config:

# Enable the geographic Map
map:

# WebServer
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http_base_url
  server_port: !secret http_server_port
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

#duckdns:
#  domain: !secret duckdns_domain
#  access_token: !secret duckdns_access_token

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# MQTT Broker
mqtt:
#  broker: localhost
#  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_password

# Emulated Hue Bridge
emulated_hue:
  listen_port: 8300
  exposed_domains:
    - light
    - switch

# Misc
sun:
media_extractor:

# IFTTT service
ifttt:
  key: !secret ifttt_key

sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
switch: !include switch.yaml
light: !include light.yaml
remote: !include remote.yaml
media_player: !include media_player.yaml
cast: !include cast.yaml
scene: !include scene.yaml
climate: !include climate.yaml
#weather: !include weather.yaml
zone: !include zone.yaml
group: !include_dir_named group/
notify: !include notify.yaml
automation: !include_dir_list automation/
script: !include script.yaml
alarm_control_panel: !include alarm_control_panel.yaml
telegram_bot: !include telegram_bot.yaml
google_assistant: !include google_assistant.yaml
logi_circle: !include logi_circle.yaml
xiaomi_aqara: !include xiaomi_aqara.yaml
vacuum: !include vacuum.yaml
panel_iframe: !include panel_iframe.yaml
owntracks: !include owntracks.yaml
