homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.358256
  longitude: 6.160630
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 156
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

system_health:

logger: !include logger.yaml

# Enable the frontend
frontend:
  themes:
    clear: !include themes/clear.yaml
    clear_dark: !include themes/clear_dark.yaml
    midnight: !include themes/midnight.yaml
    darkcyan: !include themes/darkcyan.yaml

# Enable Hassio configuration
hassio:

# Enable configuration UI
config:

# Enable the geographic Map
map:

# WebServer
http:
  base_url: !secret http_base_url
  server_port: !secret http_server_port
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

lovelace:
  mode: yaml

# MQTT Broker
mqtt:
  broker: localhost
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Emulated Hue Bridge
emulated_hue:
  listen_port: 8300
  exposed_domains:
    - light
    - switch

# Misc
sun:
media_extractor:
python_script:

# IFTTT service
ifttt:
  key: !secret ifttt_key

alarm_control_panel: !include alarm_control_panel.yaml
automation: !include_dir_list automation/
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
cast: !include cast.yaml
climate: !include climate.yaml
device_tracker: !include device_tracker.yaml
google_assistant: !include google_assistant.yaml
group: !include_dir_named group/
input_boolean: !include input_boolean.yaml
light: !include light.yaml
# logi_circle: !include logi_circle.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
owntracks: !include owntracks.yaml
panel_iframe: !include panel_iframe.yaml
plant: !include plant.yaml
remote: !include remote.yaml
scene: !include scene.yaml
script: !include script.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
telegram_bot: !include telegram_bot.yaml
timer: !include timer.yaml
vacuum: !include vacuum.yaml
# weather: !include weather.yaml
yeelight: !include yeelight.yaml
zone: !include zone.yaml
