- platform: nmap_tracker
  hosts: 192.168.254.100/28
  interval_seconds: 60
  track_new_devices: true

- platform: nmap_tracker
  hosts: 192.168.254.220/26
  interval_seconds: 300

- platform: bluetooth_tracker
  interval_seconds : 30

- platform: owntracks_http
  max_gps_accuracy: 200
