- platform: mqtt
  name: mp_bed_light
  state_topic: "stat/bedlight/POWER"
  command_topic: "cmnd/bedlight/POWER"
  qos: 2
  retain: true

- platform: yeelight
  devices:
    192.168.254.238:
      name: Ambient Yeelight
      transition: 1000
      use_music_mode: True #defaults to False
      save_on_change: False #defaults to True

- platform: yeelight
  devices:
    192.168.254.237:
      name: Sofa Yeelight Strip
      transition: 1000
      use_music_mode: True #defaults to False
      save_on_change: False #defaults to True
