- platform: mqtt
  unique_id: shp5_power
  name: "Bedlight Julie"
  state_topic: "stat/shp5/POWER1"
  command_topic: "cmnd/shp5/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: template
  lights:
    toilet:
      friendly_name: 'Toilet light'
      value_template: '{{ states("switch.0x00158d0001a4c24e_switch") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.0x00158d0001a4c24e_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.0x00158d0001a4c24e_switch
