- platform: mqtt
  name: mp_bed_light
  state_topic: "stat/bedroom_light/POWER"
  command_topic: "cmnd/bedroom_light/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: yeelight
  devices:
    192.168.254.238:
      name: Ambient Yeelight
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
