# be careful to not change names inside the Google Home app
- platform: universal
  name: Television
  children:
    - remote.harmony_hub
  commands:
    turn_on:
      service: remote.turn_on
      data:
        entity_id: remote.harmony_hub
        activity: "24399786"
    turn_off:
      service: remote.turn_off
      data:
        entity_id: remote.harmony_hub
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        command: VolumeUp
        device: "42051938"
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        command: VolumeDown
        device: "42051938"
    volume_mute:
      service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        command: Mute
        device: "42051938"
  attributes:
    state: remote.harmony_hub
    is_volume_muted: false

- platform: androidtv
  host: 192.168.254.103
  name: "Freebox mini 4k"
  adb_server_ip: 127.0.0.1
  adb_server_port: 5037
