# Temperature
- platform: mqtt
  name: "Bedroom Temperature"
  state_topic: "tele/bedroom_light/SENSOR"
  qos: 0
  value_template: "{{ value_json['DHT22'].Temperature }}"
  unit_of_measurement: "°C"

# Humidity Sensor
- platform: mqtt
  name: "Bedroom Humidity"
  state_topic: "tele/bedroom_light/SENSOR"
  qos: 0
  value_template: "{{ value_json['DHT22'].Humidity }}"
  unit_of_measurement: "%"

- platform: yweather
  name: "Weather"
  woeid: 613836
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature

#- platform: miflora
#  mac: C4:7C:8D:62:E8:72
#  name: Flower
#  force_update: false




# Temperature
- platform: mqtt
  name: "Photo Frame Temperature"
  state_topic: "photo_frame/SENSOR"
  qos: 0
  value_template: "{{ value_json.Temperature }}"
  unit_of_measurement: "°C"

# Humidity Sensor
- platform: mqtt
  name: "Photo Frame Humidity"
  state_topic: "photo_frame/SENSOR"
  qos: 0
  value_template: "{{ value_json.Humidity }}"
  unit_of_measurement: "%"

- platform: template
  sensors:
    is_someone_home:
      value_template: >
        {% if is_state('device_tracker.mp_z3c', 'home') or is_state('device_tracker.mp_macbook_air', 'home') or is_state('device_tracker.jc_iphone', 'home') or is_state('device_tracker.jc_macbook_air', 'home') %}
          yes
        {% else %}
          no
        {% endif %}

- platform: citybikes
  name: Nancy Stations
  stations:
    - 10cd7436fee13bc82f9a1de82d55ae2f
