# Uptime
- platform: uptime
  unit_of_measurement: minutes

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use
    - type: swap_use
    - type: disk_use
      arg: /
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0

# Temperature
- platform: mqtt
  name: "Bedroom Temperature"
  state_topic: "tele/bedlight/SENSOR"
  qos: 0
  value_template: "{{ value_json.SI7021.Temperature - 2 }}"
  unit_of_measurement: "°C"

# Humidity Sensor
- platform: mqtt
  name: "Bedroom Humidity"
  state_topic: "tele/bedlight/SENSOR"
  qos: 0
  value_template: "{{ value_json.SI7021.Humidity }}"
  unit_of_measurement: "%"

- platform: twitch
  client_id: !secret twitch_client_id
  channels:
    - studiorenegade

# - platform: linky
#   username: !secret linky_username
#   password: !secret linky_password

#- platform: template
#  sensors:
#    kwh_unit_cost:
#      friendly_name: "kWh unit cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ 0.0887 * 1.20 }}"
#    kwh_daily_cost:
#      friendly_name: "kWh daily cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ (states.sensor.linky_daily_1d_consumption.state | float) * (states.sensor.kwh_unit_cost.state | float) }}"
#    kwh_monthly_cost:
#      friendly_name: "kWh monthly cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ (states.sensor.linky_monthly_current_consumption.state | float) * (states.sensor.kwh_unit_cost.state | float) }}"
#    kwh_yearly_cost:
#      friendly_name: "kWh yearly cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ (states.sensor.linky_yearly_current_consumption.state | float) * (states.sensor.kwh_unit_cost.state | float) }}"

- platform: template
  sensors:
    mapquest_api_key:
      value_template: !secret mapquest_api_key

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
