# Uptime
- platform: uptime
  unit_of_measurement: minutes

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: swap_use_percent
    - type: load_1m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

# Temperature
- platform: mqtt
  name: "Bedroom Temperature"
  state_topic: "tele/bedlight/SENSOR"
  qos: 0
  value_template: "{{ value_json['DHT22'].Temperature - 2 }}"
  unit_of_measurement: "°C"

# Humidity Sensor
- platform: mqtt
  name: "Bedroom Humidity"
  state_topic: "tele/bedlight/SENSOR"
  qos: 0
  value_template: "{{ value_json['DHT22'].Humidity }}"
  unit_of_measurement: "%"

- platform: yweather
  name: "Weather"
  woeid: 613836
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature

#- platform: miflora
#  mac: C4:7C:8D:62:E8:72
#  name: Flower
#  force_update: false

#- platform: citybikes
#  name: Nancy Stations
#  radius: 5000

- platform: waqi
  token: !secret aqicn_token
  locations:
    - Charles III, Nancy-Centre

- platform: twitch
  channels:
    - studiorenegade

#- platform: linky
#  username: !secret linky_username
#  password: !secret linky_password
#  monitored_variables:
#    - daily_1d_consumption
#    - monthly_current_consumption
#    - yearly_current_consumption

#- platform: template
#  sensors:
#    kwh_unit_cost:
#      friendly_name: "kWh unit cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ 0.0887 * 1.20 }}"
#    kwh_daily_cost:
#      friendly_name: "kWh daily cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ (states.sensor.linky_daily_1d_consumption.state | float) * (states.sensor.kwh_unit_cost.state | float) }}"
#    kwh_monthly_cost:
#      friendly_name: "kWh monthly cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ (states.sensor.linky_monthly_current_consumption.state | float) * (states.sensor.kwh_unit_cost.state | float) }}"
#    kwh_yearly_cost:
#      friendly_name: "kWh yearly cost"
#      unit_of_measurement: '€'
#      icon_template: mdi:currency-eur
#      value_template: "{{ (states.sensor.linky_yearly_current_consumption.state | float) * (states.sensor.kwh_unit_cost.state | float) }}"


#- platform: speedtest
#  hour:
#    - 8
#    - 12
#    - 16
#    - 20
#  monitored_conditions:
#    - ping
#    - download
#    - upload

