- platform: mqtt
  name: Smart Power Socket
  state_topic: "stat/switch/POWER"
  command_topic: "cmnd/switch/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  unique_id: shp5_usb
  state_topic: "stat/shp5/POWER2"
  command_topic: "cmnd/shp5/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: template
  switches:
    chromecast:
      value_template: "{% if is_state('remote.harmony_hub.current_activity', 'Chromecast') %}on{% else %}off{% endif %}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: "24745598"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
    sound:
      value_template: false
      turn_on:
        - service: remote.send_command
          data_template:
            entity_id: remote.harmony_hub
            command: Mute
            device: 42051938
      turn_off:
        - service: remote.send_command
          data_template:
            entity_id: remote.harmony_hub
            command: Mute
            device: 42051938
