title: Bibous Home
background: center / cover no-repeat url("/local/themes/clear_background.jpeg") fixed
views:
  - !include lovelace/views/rooms.yaml
  - !include lovelace/views/people.yaml
  - !include lovelace/views/raspberry.yaml
  - !include lovelace/views/alarm.yaml
