alias: "Alarm armed"
trigger:
  platform: state
  entity_id: alarm_control_panel.ha_alarm
  to: armed_away
action:
  - service: telegram_bot.send_message
    data: 
      message: "Alarm armed"
      target:
        - !secret telegram_mp_chat_id
  - service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: "Alarme activée"
      language: "fr"
  - service: script.turn_off
    entity_id: script.flash_light
  - service: script.turn_off
    entity_id: script.flash_light_loop
  - service: light.turn_on
    data:
      entity_id: light.gateway_light_f0b429cc58ea
      brightness: 255
      color_name: red