alias: "Alarm disarmed"
trigger:
  platform: state
  entity_id: alarm_control_panel.ha_alarm
  to: disarmed
action:
#  - service: telegram_bot.send_message
#    data:
#      message: "Alarm disarmed"
#      target:
#        - !secret telegram_mp_chat_id
  - service: script.turn_off
    entity_id: script.flash_light
  - service: script.turn_off
    entity_id: script.flash_light_loop
  - service: light.turn_off
    entity_id: light.yeelight_strip
  - service: notify.google_assistant
    data:
      message: "Alarme désactivée"
