alias: "Alarm triggered"
trigger:
  platform: state
  entity_id: alarm_control_panel.ha_alarm
  to: triggered
action:
  - service: telegram_bot.send_message
    data:
      title: "Alert !"
      message: "Someone passed the door !"
      target:
        - !secret telegram_mp_chat_id
        - !secret telegram_jc_chat_id
      inline_keyboard:
        - "Disarm:/disarm"
  - service: script.flash_light
    data:
      light_entity_id: 'light.gateway_light_f0b429cc58ea'
  - service: tts.google_say
    entity_id: media_player.google_home
    data:
      message: "Alerte ! Un intrus est arrivé"
      language: "fr"
  - service: tts.google_say
    entity_id: media_player.google_home_mini
    data:
      message: "Alerte ! Un intrus est arrivé"
      language: "fr"
  - service: tts.google_say
    entity_id: media_player.enceintes
    data:
      message: "Alerte ! Un intrus est arrivé"
      language: "fr"
