alias: "Trigger alarm"
trigger:
  platform: state
  entity_id: binary_sensor.door_window_sensor_158d0001a64dd9
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm
