alias: "Alarm triggered"
trigger:
  platform: state
  entity_id: alarm_control_panel.ha_alarm
  to: triggered
action:
  - service: telegram_bot.send_message
    data:
      title: "Alert !"
      message: "Someone passed the door !"
      target:
        - !secret telegram_mp_chat_id
        - !secret telegram_jc_chat_id
      inline_keyboard:
        - "Disarm:/disarm"
  - service: light.turn_on
    data:
      entity_id: light.ambient_yeelight
      brightness: 255
      color_name: red
  - service: script.flash_light
    data:
      light_entity_id: 'light.ambient_yeelight'
  - service: notify.google_assistant
    data:
      message: "Alerte ! Un intrus est arrivé. Déclenchement immédiat des appels auprès des services de sécurité et démarrage de la séquence d'enregistrement vidéo."
