alias: "Window still open"
trigger:
  platform: state
  entity_id: binary_sensor.door_window_sensor_158d0001a1f304
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001a64dd9
    state: "on"
action:
  - service_template: >
      {% if "matthieu" in ([states.group.matthieu, states.group.julie] | selectattr('state', 'equalto', 'home') | first).entity_id %}
      notify.telegram_mp
      {% else %}
      notify.telegram_jc
      {% endif %}
    data:
      message: "Don't forget to close the bedroom window in your way out !"
