alias: "Window has been opened for too long"
trigger:
  platform: state
  entity_id: binary_sensor.door_window_sensor_158d0001a64dd9
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: 30
    seconds: 0
action:
  - service_template: >
      {% if "matthieu" in ([states.group.matthieu, states.group.julie] | selectattr('state', 'equalto', 'home') | first).entity_id %}
      notify.telegram_mp
      {% else %}
      notify.telegram_jc
      {% endif %}
    data:
      message: "Bedroom window has been open for {{ ((as_timestamp(now()) - as_timestamp(states.binary_sensor.door_window_sensor_158d0001a64dd9.last_changed)) / 60) | int }} minutes"
