alias: "Turn lights on when someone comes home"
trigger:
  platform: state
  entity_id: binary_sensor.door_window_sensor_158d0001a64dd9
  from: "off"
  to: "on"
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: 'binary_sensor.is_someone_home'
        state: 'off'
      - condition: template
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.is_someone_home.last_updated) < 300 }}'
  - condition: numeric_state
    entity_id: sensor.illumination_f0b429cc58ea
    below: 150
  - condition: state
    entity_id: group.all_lights
    state: 'off'
action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_ceiling
#  - wait_template: "{{ is_state('binary_sensor.door_window_sensor_158d0001a64dd9', 'off') }}"
#    timeout: "00:00:30"
  - service: notify.google_assistant
    data_template:
      message: >
        Bienvenue {% for user in [states.group.matthieu, states.group.julie] if user.state == "home" %}{{ user.attributes.friendly_name }}{% if not loop.last %} et {% endif %}{% endfor %} à la maison. J'ai allumé la lumière pour vous.
