
alias: "Server is using too much RAM"
trigger:
  platform: numeric_state
  entity_id: sensor.memory_use
  above: 850
  for:
    hours: 0
    minutes: 2
    seconds: 0
action:
  - service: notify.telegram_mp
    data:
      message: "Server is using too much RAM !"
