alias: "GeekInc started"
trigger:
  platform: state
  entity_id: sensor.geekinc
  to: streaming
condition:
  - condition: state
    entity_id: binary_sensor.is_someone_home
    state: "on"
  - condition: time
    after: '20:45:00'
    before: '22:00:00'
    weekday:
      - wed
      - fri
action:
  - service: script.turn_on
    entity_id: script.geek_inc
  - service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: "C'est l'heure de GeekInc"
      language: "fr"
