alias: "Vacuum state changed"
trigger:
  platform: state
  entity_id: vacuum.xiaomi_mi_robot
condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
  - condition: state
    entity_id: binary_sensor.is_someone_home
    state: "off"
action:
  - service: telegram_bot.send_message
    data_template:
      message: "Vacuum {{ 'has started' if trigger.to_state.state == 'on' else 'has ended' }}"
      target:
        - !secret telegram_mp_chat_id
        - !secret telegram_jc_chat_id
