alias: "Washing done"
trigger:
  platform: state
  entity_id: binary_sensor.washing_machine
  from: "on"
  to: "off"
  for:
    hours: 0
    minutes: 0
    seconds: 10
action:
  - service: telegram_bot.send_message
    data: 
      message: "Washing is done"
      target:
        - !secret telegram_mp_chat_id
        - !secret telegram_jc_chat_id
  - condition: state
    entity_id: binary_sensor.is_someone_home
    state: "on"
  - service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: "Le linge est propre"
      language: "fr"
