alias: "Window has been opened for too long"
trigger:
  platform: state
  entity_id: binary_sensor.door_window_sensor_158d0001a64dd9
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: 30
    seconds: 0
action:
  - service: telegram_bot.send_message
    data_template:
      message: "Bedroom window has been opened for {{ ( states.binary_sensor.door_window_sensor_158d0001a64dd9.attributes['Open since'] / 60) | int }} minutes"
      target:
        - !secret telegram_mp_chat_id
#        - !secret telegram_jc_chat_id
