alias: "IFTTT Webhook received"
trigger:
  platform: event
  event_type: ifttt_webhook_received
  event_data:
    action: call_service
action:
  service_template: "{{ trigger.event.data.service }}"
  data_template:
    message: "{{ trigger.event.data.message }}"
