alias: "Everybody is away"
trigger:
  platform: state
  entity_id: binary_sensor.is_someone_home
  from: "on"
  to: "off"
action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.ha_alarm
  - condition: numeric_state
    entity_id: sensor.uptime
    above: 1
  - service_template: >
      {% if "matthieu" in ([states.group.matthieu, states.group.julie] | sort(attribute="last_changed") | first).entity_id %}
      notify.telegram_mp
      {% else %}
      notify.telegram_jc
      {% endif %}
    data_template:
      message: >
        {% set user = ([states.group.matthieu, states.group.julie] | sort(attribute="last_changed") | last) %}
        {{ user.attributes.friendly_name }} just left home and is {{ user.state }}
