alias: "Someone is moving"
trigger:
  platform: state
  entity_id: device_tracker.jc_iphone
condition:
# don't send a notification if
# - someone is not moving
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
# - everybody is now home
  - condition: template
    value_template: "{{ not (is_state('group.matthieu', 'home') and is_state('group.julie', 'home')) }}"
# - someone is leaving the other in a zone
  - condition: template
    value_template: "{{ not (trigger.from_state.state != 'not_home' and (('jc' in trigger.to_state.entity_id and is_state('device_tracker.mp_s9', trigger.from_state.state)) or ('mp' in trigger.to_state.entity_id and is_state('device_tracker.jc_iphone', trigger.from_state.state)))) }}"
# - someone is joining the other at home
  - condition: template
    value_template: "{{ not (trigger.to_state.state == 'home' and is_state('device_tracker.mp_s9.state', states.device_tracker.jc_iphone.state)) }}"
action:
  - service_template: >
      {% if 'mp' in trigger.to_state.entity_id %}
      notify.telegram_jc
      {% else %}
      notify.telegram_mp
      {% endif %}
    data_template:
      message: >
        {{ 'Matthieu' if 'mp' in trigger.to_state.entity_id else 'Julie' }} is {{ ('leaving ' + trigger.from_state.state) if trigger.to_state.state == 'not_home' else 'at ' + (trigger.to_state.state) }}
