alias: "Set Matthieu GPS to home when arriving"
trigger:
  platform: state
  entity_id: group.matthieu
  to: 'home'
condition:
  # and MP's GPS is not reaching home
  - condition: template
    value_template: "{{ not is_state('device_tracker.mp_s9','home') }}"
action:
  - service: device_tracker.see
    data_template:
      dev_id: mp_s9
      gps: 
        - '{{states.zone.home.attributes.latitude}}'
        - '{{states.zone.home.attributes.longitude}}'
      gps_accuracy: 100
