alias: "Set Julie GPS to home when arriving"
trigger:
  platform: state
  entity_id: group.julie
  from: 'not_home'
  to: 'home'
condition:
  # and JC's GPS is not reaching home
  - condition: state
    entity_id: device_tracker.jc_iphone
    state: 'not_home'
action:
  - service: device_tracker.see
    data_template:
      dev_id: jc_iphone
      gps: 
        - '{{states.zone.home.attributes.latitude}}'
        - '{{states.zone.home.attributes.longitude}}'
      gps_accuracy: 100
