alias: "Set Julie GPS to home when arriving"
trigger:
  platform: state
  entity_id: group.julie
  to: 'home'
condition:
  # and JC's GPS is not reaching home
  - condition: template
    value_template: "{{ not is_state('device_tracker.jc_iphone','home') }}"
action:
  - service: device_tracker.see
    data_template:
      dev_id: jc_iphone
      gps:
        - '{{states.zone.home.attributes.latitude}}'
        - '{{states.zone.home.attributes.longitude}}'
      gps_accuracy: 100
